Updating package and install scripts. Adding a new package-cct script.

diff --git a/cct b/cct
--- a/cct
+++ b/cct
@@ -20,7 +20,12 @@ sh -c "$(curl -sSL -H "Authorization: token ${GH_PAT}" "https://raw.githubuserco
 ### Local Testing
 # sh -c "$(cat install-cct)" || sh -c "$(cat install-cct-branch)"
 
-printf "\033[93m>\033[0m Changing directory to '%s' ...\n" "${PROJECT_NAME}"
-cd "${PROJECT_NAME}"
+if [ $? -eq 0 ]; then
+    printf "\033[93m>\033[0m Changing directory to '%s' ...\n" "${PROJECT_NAME}"
+    cd "${PROJECT_NAME}"
 
-sh -c "$(cat bin/run.sh)"
+    sh -c "$(cat bin/run.sh)"
+else
+    printf "\033[91;1mThere was an error. Abort and cleanup ...\033[0m\n" >&2
+    [ -d "${PROJECT_NAME}" ] && rm -rf "${PROJECT_NAME}"
+fi
